### ISSUE TITLE
Outdated cookbook version in supermarket.

### ISSUE THREAD

**Issue by Nklya** [chef-cookbooks/chef-grafana#6]
Hello.

I've found that cookbook version in Chef supermarket is outdated. 
https://supermarket.chef.io/cookbooks/chef-grafana

In metadata version is 0.3.0, but in supermarket only 0.2.2.

Could you please update cookbook in supermarket?

**Comment by iennae** [comment]
Thanks for reporting this issue. I've updated the version on the supermarket.

**Comment by Nklya** [comment]
Thanks!
